# productionブランチにPRがマージされたときにGASの本番環境に自動プッシュし、
# 紐づいているGASのデプロイIDに新しいバージョンで自動デプロイするAction
---
name: Production Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - production
      - release
    types:
      - closed
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/deploy.yaml'

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    permissions:
      contents: read
    uses: ./.github/workflows/deploy.yaml
    secrets:
      ACCESS_TOKEN: ${{ secrets.PROD_ACCESS_TOKEN || secrets.ACCESS_TOKEN }}
      ID_TOKEN: ${{ secrets.PROD_ID_TOKEN || secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.PROD_REFRESH_TOKEN || secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.PROD_CLIENT_ID || secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.PROD_CLIENT_SECRET || secrets.CLIENT_SECRET }}
      SCRIPT_ID: ${{ secrets.PROD_SCRIPT_ID || secrets.SCRIPT_ID }}
      DEPLOYMENT_ID: ${{ secrets.PROD_DEPLOYMENT_ID || secrets.DEPLOYMENT_ID }}
