# main、feature、fixブランチにコミットがプッシュされたときにGASの検証環境に自動プッシュするAction
---
name: Deployment Push Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - 'feature/**'
      - 'fix/**'
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'yarn.lock'
      - '.github/workflows/deploy.yaml'

permissions: {}

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    permissions:
      contents: read
    uses: ./.github/workflows/deploy.yaml
    secrets:
      ACCESS_TOKEN: ${{ secrets.DEV_ACCESS_TOKEN || secrets.ACCESS_TOKEN }}
      ID_TOKEN: ${{ secrets.DEV_ID_TOKEN || secrets.ID_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.DEV_REFRESH_TOKEN || secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.DEV_CLIENT_ID || secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET || secrets.CLIENT_SECRET }}
      SCRIPT_ID: ${{ secrets.DEV_SCRIPT_ID || secrets.SCRIPT_ID }}
